"""
================================================================================
STRATEGY-DRIVEN ATTACK NODE
================================================================================

DEVELOPER INSTRUCTIONS:
--------------------------------------------------------------------------------
1. Architectural Role: This is a Strategy-Delegation Node. It does NOT contain
   LLM logic. It strictly delegates generation to the injected strategy.
2. Inheritance: Inherits directly from BaseAdversarialNode (StrategyProxyNode 
   is deprecated and removed).
3. State Handling: It receives the state delta generated by the strategy and 
   passes it back to the WorkflowEngine.
4. Type Safety: Uses strict SystemState typing and explicit dictionary access.
================================================================================
"""

from typing import Dict, Any
from nodes.base import BaseAdversarialNode
from engine.state import SystemState
from core.logging import debug, tracer, step, warn, err


class StrategyDrivenAttackNode(BaseAdversarialNode):
    """
    Attack node that fully delegates to an injected strategy.
    
    The strategy is responsible for:
    - Making LLM calls (single or multiple)
    - Processing data
    - Managing complex workflows
    - Storing intermediate results
    
    This node simply wraps the strategy's `execute_generation` method.
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """Initialize attack node and extract static params."""
        super().__init__(config)
        # Extract static node_params in case future pre/post-processing needs them
        self.node_params = self.config["node_params"] if "node_params" in self.config else {}
    
    async def execute(self, state: SystemState, runtime_config: Dict[str, Any] = None) -> Dict[str, Any]:
        if runtime_config is None: runtime_config = {}
        tracer("StrategyDrivenAttackNode.execute")
        
        # STRICT CONFIG ACCESS: Fail fast if the Builder didn't inject the strategy
        if "strategy" not in self.config:
            err("Strategy instance not found in Attack Node config")
            raise AttributeError("Strategy instance not found in Attack Node's self.config.")
            
        strategy = self.config["strategy"]
        
        debug("Delegating to strategy execute_generation", strategy_type=type(strategy).__name__)
        
        # Explicit delegation: Pass both the strict state and the dynamic runtime_config
        result_delta = await strategy.execute_generation(state, runtime_config)
        
        step("Attack generation complete", result_keys=list(result_delta.keys()))
        return result_delta

    @classmethod
    def get_node_schema(cls) -> Dict[str, Any]:
        """
        Return JSON schema describing the node's parameters.
        """
        return {
            "type": "object",
            "properties": {},
            "description": "Attack node delegates entirely to strategy.execute_generation(). No node-specific params."
        }